version: '3'
services:
  auditlimit:
    image: lyy0709/auditlimit
    restart: always
    ports:
      - "127.0.0.1:9611:8080"
    volumes:
      - ./data:/app/data
    environment:
      PORT: 9611
      OAIKEY: "" # OpenAI API key 用于内容审核
      CHATGPT-AUTO: "200/3h"
      CHATGPT-TEXT-DAVINCI-002-RENDER-SHA: "200/3h"
      CHATGPT-GPT-4O-MINI: "200/3h"
      CHATGPT-GPT-4O: "60/3h"
      CHATGPT-GPT-4: "20/3h"
      CHATGPT-GPT-4O-CANMORE: "30/3h"
      CHATGPT-O1-PREVIEW: "7/24h"
      CHATGPT-O1-MINI: "50/24h"
      CHATGPT-GPT-5: "60/3h"
      CLAUDE-CLAUDE-3-7-SONNET: "20/3h"
      CLAUDE-CLAUDE-3-5-HAIKU: "20/3h"
      CLAUDE-CLAUDE-4-1-OPUS: "20/3h"
      CLAUDE-CLAUDE-4-OPUS: "20/3h"
      CLAUDE-CLAUDE-4-SONNET: "20/3h"
      CLAUDE-CLAUDE-3-OPUS: "20/3h"
      GROK-GROK-3: "20/3h"
      GROK-GROK-4: "20/3h"
      GROK-GROK-4-AUTO: "20/3h"
    